import { z } from 'zod';
import { openai } from './openai';
import { prisma } from './prisma';

// ─── Schemas ──────────────────────────────────────────────────────────────────

export const VisualPromptSchema = z.object({
  subject: z.string(),          // who/what is in frame
  action: z.string(),           // what's happening
  cameraAngle: z.string(),      // e.g. "extreme low angle, 24mm"
  lighting: z.string(),         // e.g. "harsh midday sun, deep shadows"
  colorGrade: z.string(),       // e.g. "warm golden tones, rich saturation"
  doNotInclude: z.string(),     // explicit exclusions for video gen
});

export const SceneSchema = z.object({
  sceneNumber: z.number(),
  durationSeconds: z.literal(6),      // FIXED: every scene is exactly 6 seconds (Veo supported: 4, 6, 8)
  description: z.string(),
  visualPrompt: VisualPromptSchema,
  narration: z.string().nullable(),   // null for scenes that should be silent
  onScreenText: z.string().nullable(), // null unless text overlay is needed
  isCTAScene: z.boolean(),            // ONLY true for scene 3
  emotionBeat: z.string(),            // what viewer feels in this moment
});

export const VoiceoverScriptSchema = z.object({
  fullScript: z.string(),             // complete VO as one continuous piece
  voiceTone: z.string(),              // single tone applied to entire ad
  sceneAssignments: z.record(         // "scene_1": "line..." | null
    z.string(),
    z.string().nullable()
  ),
});

export const VoiceTypeSchema = z.object({
  gender: z.enum(['male', 'female']).catch('female'),
  tone: z.enum(['energetic', 'calm', 'authoritative']).catch('calm'),
  pace: z.enum(['fast', 'medium', 'slow']).catch('medium'),
});

export const AdConceptSchema = z.object({
  hook: z.string(),
  emotion: z.string(),
  narrativeArc: z.string(),
  cta: z.string(),                    // appears in output ONCE, in last scene only
  visualStyle: z.object({
    camera: z.string(),
    colorGrade: z.string(),
    editingRhythm: z.string(),
    doNotInclude: z.string(),
  }),
  scenes: z.array(SceneSchema).length(3), // FIXED: exactly 3 scenes, no more, no less
  voiceoverScript: VoiceoverScriptSchema,
  voiceType: VoiceTypeSchema,
  musicMood: z.enum(['upbeat', 'dramatic', 'calm', 'tense', 'nostalgic']).catch('upbeat'),
  tagline: z.string(),
  /**
   * Single aesthetic constraint string prepended to ALL Veo prompts.
   * Locks lighting, color grade, camera style, and time-of-day so all 3 clips
   * share one visual identity. Generated by GPT alongside the scene plan.
   * Format: "[lighting]. [color grade]. [camera style]. [setting/time]." (1 sentence each)
   */
  masterStyleGuide: z.string().optional(),
});

export const WinningPatternSchema = z.object({
  hook_styles: z.array(z.string()).optional(),
  visual_patterns: z.array(z.string()).optional(),
  emotional_triggers: z.array(z.string()).optional(),
  avoid: z.array(z.string()).optional(),
});

export type Scene = z.infer<typeof SceneSchema>;
export type AdConcept = z.infer<typeof AdConceptSchema>;
export type WinningPattern = z.infer<typeof WinningPatternSchema>;

export type IdeationPromptResult = {
  idea: string;
};

export const Category2ProductAnalysisSchema = z.object({
  product_name: z.string(),
  brand_name: z.string(),
  category: z.string(),
  primary_color: z.string(),
  contrast_color: z.string(),
  hero_sensory_element: z.string(),
  impact_moment: z.string(),
  flying_elements: z.string(),
  surface: z.string(),
  color_grade: z.string(),
  tagline: z.string(),
});

export const Category2QualityGateSchema = z.object({
  passes: z.boolean(),
  violations: z.array(z.string()),
  fixed_prompt: z.string(),
});

export type Category2ProductAnalysis = z.infer<typeof Category2ProductAnalysisSchema>;
export type Category2QualityGateResult = z.infer<typeof Category2QualityGateSchema>;

function stripJsonCodeFences(value: string): string {
  return value.replace(/```json|```/gi, '').trim();
}

function buildCategory2AnalysisSystemPrompt(): string {
  return `You are a product analyst for an AI ad generation platform.
Your job is to extract structured data from a product description.
Return ONLY valid JSON. No preamble. No markdown. No explanation.

Extract the following fields:

{
  "product_name": "Full product name",
  "brand_name": "Brand name only",
  "category": "Food / Beverage / Footwear / Wellness / Other",
  "primary_color": "Main brand/product color (e.g. 'electric blue', 'deep red')",
  "contrast_color": "Best contrasting color for background (e.g. 'jet black', 'icy white')",
  "hero_sensory_element": "The ONE thing that makes this product feel premium (e.g. 'cold mist', 'rich cocoa', 'soft leather')",
  "impact_moment": "The most dramatic visual moment possible for this product (e.g. 'can cracking open with frost explosion', 'oats cascading in slow-mo', 'sole hitting wet court')",
  "flying_elements": "Ingredients or materials that can orbit/fly around product (e.g. 'coffee beans, cocoa powder, ice shards')",
  "surface": "What surface should product land/sit on (e.g. 'block of ice', 'marble slab', 'concrete floor')",
  "color_grade": "Overall color temperature (e.g. 'warm mocha amber', 'icy cool blue-white', 'vibrant tropical')",
  "tagline": "A 3-5 word punchy tagline for end card"
}`;
}

function buildCategory2VideoBriefSystemPrompt(): string {
  return `You are a world-class video ad director specializing in scroll-stopping
short-form product ads for Instagram, TikTok, and YouTube Shorts.

You write video prompts for AI video generation tools (Veo 3 / Kling 3.0).

Your ads follow ONE philosophy:
"Assault the viewer's visual cortex with the product in the first 0.5 seconds.
Then don't let them breathe."

ABSOLUTE RULES - NEVER VIOLATE:
1. Product must be FULLY VISIBLE and BRAND READABLE within the first 0.5 seconds
2. Maximum shot duration: 1.5 seconds. After that, cut.
3. Minimum 3 different environments/backgrounds across the full video
4. Most dramatic moment MUST be in the first 1 second - never saved for the end
5. NO slow macro pans. NO product spinning with droplets. NO hands entering slowly.
6. NO dark moody "late night bar" lighting. Bright. High contrast. High saturation.
7. NO building atmosphere before showing product. Product IS the atmosphere.

VIDEO STRUCTURE (8-18 seconds):
- 0.0s-0.5s : HERO SHOT - Full product on [surface], brand facing camera, [impact_moment] happening RIGHT NOW
- 0.5s-1.5s : JUMP CUT - Product against [contrast_color] background, [flying_elements] orbiting in slow-mo
- 1.5s-3.0s : JUMP CUT - Extreme macro of [hero_sensory_element], hypermotion, fills entire frame
- 3.0s-5.0s : ENVIRONMENT HOP - Product in natural context (NOT a kitchen/living room - a dramatic version: frozen tundra, sun-soaked terrace, rain-slicked street)
- 5.0s-7.0s : SENSORY CLIMAX - [impact_moment] in full slow-motion with particles/mist/splash
- 7.0s-END  : END CARD - Black screen. Brand name. Tagline. Clean.

COLOR DIRECTION:
- Dominant: [primary_color]
- Background contrast: [contrast_color]
- Grade: [color_grade]
- Saturation: +30% above natural. This needs to POP on a bright phone screen.

AUDIO DIRECTION:
- 0.0s-5.0s: No voiceover. Let impact sounds carry (thud, crack, pour, rustle)
- 5.0s-7.0s: Deep bass swell under the sensory climax
- END CARD: Silence. Then 1 clean sound effect (chime, click, or deep tone)
- Optional narration: ONE line only, spoken at the sensory climax moment: "[tagline]"

FORBIDDEN SHOTS LIST:
Product rotating slowly in mid-air with water droplets
Macro pan that takes more than 1 second to reveal what the product is
Hands mixing, pouring in sequence, assembling anything
Kitchen / gym / bedroom lifestyle context
"Before and after" structure
Tutorial or step-by-step process of any kind
Dark moody grade as the dominant look`;
}

function buildCategory2VideoBriefUserPrompt(productVars: Category2ProductAnalysis): string {
  return `Generate a complete video prompt for this product:

Product: ${productVars.product_name}
Brand: ${productVars.brand_name}
Category: ${productVars.category}
Primary Color: ${productVars.primary_color}
Contrast Color: ${productVars.contrast_color}
Hero Sensory Element: ${productVars.hero_sensory_element}
Impact Moment: ${productVars.impact_moment}
Flying Elements: ${productVars.flying_elements}
Surface: ${productVars.surface}
Color Grade: ${productVars.color_grade}
Tagline: ${productVars.tagline}

Output format:
- A single continuous video prompt paragraph ready to paste into Veo/Kling
- Followed by a "SHOT LIST" section with timestamp-by-timestamp breakdown
- Followed by "AUDIO NOTES" section`;
}

function buildCategory2QualityGateSystemPrompt(): string {
  return `You are a quality checker for AI-generated video ad prompts.
Review the following video prompt and check it against this checklist.
Return ONLY valid JSON. No explanation.

{
  "passes": true/false,
  "violations": ["list any rule violations found"],
  "fixed_prompt": "corrected version of the prompt if violations found, else repeat original"
}

CHECKLIST - Flag as violation if ANY of these are present:
- Product not visible in first 0.5 seconds
- Any single shot described as longer than 1.5 seconds (except end card)
- Fewer than 3 environments mentioned
- Most dramatic moment placed after the 3 second mark
- Any mention of "hands", "pouring sequence", "mixing", "assembling"
- Any mention of "dark", "moody", "dimly lit" as the dominant grade
- Product described as "spinning slowly" or "rotating with droplets"
- Any lifestyle room context (kitchen, bedroom, gym interior)`;
}

async function runCategory2PromptChain(productDescription: string): Promise<{
  productVars: Category2ProductAnalysis;
  finalPrompt: string;
  qcReport: Category2QualityGateResult;
}> {
  const analysisResponse = await openai.chat.completions.create({
    model: 'gpt-4o',
    max_tokens: 1000,
    response_format: { type: 'json_object' },
    messages: [
      { role: 'system', content: buildCategory2AnalysisSystemPrompt() },
      { role: 'user', content: productDescription },
    ],
  });

  const rawAnalysis = stripJsonCodeFences(analysisResponse.choices[0]?.message?.content ?? '{}');
  const productVars = Category2ProductAnalysisSchema.parse(JSON.parse(rawAnalysis));

  const briefResponse = await openai.chat.completions.create({
    model: 'gpt-4o',
    max_tokens: 2000,
    messages: [
      { role: 'system', content: buildCategory2VideoBriefSystemPrompt() },
      { role: 'user', content: buildCategory2VideoBriefUserPrompt(productVars) },
    ],
  });

  const generatedPrompt = (briefResponse.choices[0]?.message?.content ?? '').trim();

  const qcResponse = await openai.chat.completions.create({
    model: 'gpt-4o',
    max_tokens: 1000,
    response_format: { type: 'json_object' },
    messages: [
      { role: 'system', content: buildCategory2QualityGateSystemPrompt() },
      { role: 'user', content: generatedPrompt },
    ],
  });

  const rawQc = stripJsonCodeFences(qcResponse.choices[0]?.message?.content ?? '{}');
  const qcReport = Category2QualityGateSchema.parse(JSON.parse(rawQc));

  return {
    productVars,
    finalPrompt: qcReport.passes ? generatedPrompt : qcReport.fixed_prompt,
    qcReport,
  };
}

function buildCategory2ConceptFromChain(
  productName: string,
  targetAudience: string,
  chain: {
    productVars: Category2ProductAnalysis;
    finalPrompt: string;
    qcReport: Category2QualityGateResult;
  },
): AdConcept {
  const { productVars, finalPrompt } = chain;

  const conceptCandidate = {
    hook: `${productVars.product_name} is fully visible in the first 0.5s with ${productVars.impact_moment}.`,
    emotion: 'High-impact sensory anticipation',
    narrativeArc: 'front-loaded climax -> rapid sensory escalation -> branded close',
    cta: productVars.tagline,
    visualStyle: {
      camera: 'Hard jump cuts, high-speed inserts, and fast macro transitions',
      colorGrade: productVars.color_grade,
      editingRhythm: 'Maximum 1.5s per shot, aggressive jump-cut pacing',
      doNotInclude: 'slow macro pans, rotating product with droplets, hands, pouring sequence, mixing, assembling, kitchen, bedroom, gym, dark moody dominant lighting',
    },
    scenes: [
      {
        sceneNumber: 1,
        durationSeconds: 6,
        description: `Front-loaded product reveal with immediate dramatic impact for ${targetAudience}.`,
        visualPrompt: {
          subject: `${productVars.product_name} fully visible and brand-readable on ${productVars.surface}.`,
          action: `${productVars.impact_moment}; then jump cut to ${productVars.contrast_color} backdrop with ${productVars.flying_elements} orbiting.`,
          cameraAngle: 'Start front-on hero framing, then sharp cuts into dynamic close-ups',
          lighting: 'Bright, high-contrast, high-saturation commercial lighting',
          colorGrade: productVars.color_grade,
          doNotInclude: 'Any slow reveal, dark moody dominant grade, hands or step-by-step prep',
        },
        narration: null,
        onScreenText: null,
        isCTAScene: false,
        emotionBeat: 'Immediate visual overload and brand recognition',
      },
      {
        sceneNumber: 2,
        durationSeconds: 6,
        description: 'Sensory escalation through macro detail and environment hops.',
        visualPrompt: {
          subject: `Extreme macro of ${productVars.hero_sensory_element} and product context shifts.`,
          action: 'Cut through at least three dramatic environments with the product always dominant; trigger the sensory climax early.',
          cameraAngle: 'Alternating macro and medium inserts with fast transitions',
          lighting: 'Bright, crisp contrast with vivid saturation and clean highlights',
          colorGrade: productVars.color_grade,
          doNotInclude: 'Lifestyle rooms, tutorials, process sequencing, slow cinematic pans',
        },
        narration: productVars.tagline,
        onScreenText: null,
        isCTAScene: false,
        emotionBeat: 'Sensory intensity peaks without losing product clarity',
      },
      {
        sceneNumber: 3,
        durationSeconds: 6,
        description: 'Clean branded end card close.',
        visualPrompt: {
          subject: `Black end card with ${productVars.brand_name} and tagline lockup.`,
          action: 'Hold clean brand close with one final precise sound hit.',
          cameraAngle: 'Static graphic lockup',
          lighting: 'Clean high-contrast black card with bright readable typography',
          colorGrade: productVars.color_grade,
          doNotInclude: 'Additional storytelling beats or delayed product reveal',
        },
        narration: null,
        onScreenText: productVars.tagline,
        isCTAScene: true,
        emotionBeat: 'Clear branded retention moment',
      },
    ],
    voiceoverScript: {
      fullScript: productVars.tagline,
      voiceTone: 'Minimal and punchy',
      sceneAssignments: {
        scene_1: null,
        scene_2: productVars.tagline,
        scene_3: null,
      },
    },
    voiceType: {
      gender: 'female',
      tone: 'energetic',
      pace: 'medium',
    },
    musicMood: 'dramatic',
    tagline: productVars.tagline,
    category2Prompt: finalPrompt,
  };

  return AdConceptSchema.parse(normalizeAdConceptCandidate(conceptCandidate, productName, 'sensory'));
}

// ─── Narrative Style: Two Ad Arc Types ────────────────────────────────────────

/**
 * UGC Arc  — benefit is visible/demonstrable on camera (skincare, perfume, supplements).
 *            Structure: human problem → product solving it → emotional result.
 *
 * Craft Arc — benefit is in origin, construction, and material craft (shoes, bags, watches).
 *            Structure: raw material / origin → the making / craft → product in the world.
 *
 * Sensory Arc — benefit is experiential and should be felt, not narrated as a process.
 *               Structure: macro material reveal → sensory motion/detail → pure product payoff.
 */
export type NarrativeStyle = 'ugc' | 'craft' | 'sensory';

/**
 * Auto-classifies a product into ugc or craft narrative arc.
 * Uses keyword scoring: craft wins ties (safer default for ambiguous products).
 */
export function detectNarrativeStyle(
  productDescription: string,
  features: string = '',
  productCategory?: string,
): NarrativeStyle {
  const haystack = `${productDescription} ${features} ${productCategory ?? ''}`.toLowerCase();

  // Products whose value is in craftsmanship, origin, or durable material construction
  const craftKeywords = [
    'shoe', 'sneaker', 'boot', 'sandal', 'footwear', 'trainer', 'loafer',
    'watch', 'timepiece', 'horology',
    'bag', 'handbag', 'wallet', 'belt', 'luggage', 'purse', 'backpack',
    'jacket', 'denim', 'jeans', 'leather',
    'furniture', 'chair', 'desk', 'lamp', 'tool', 'instrument', 'camera',
  ];

  // Products whose value is sensory, consumable, or texture-led rather than process-led
  const sensoryKeywords = [
    'oat', 'cereal', 'grain', 'granola', 'bread', 'snack', 'bar', 'food',
    'coffee', 'tea', 'matcha', 'beverage', 'drink', 'juice', 'smoothie', 'latte',
    'chocolate', 'candy', 'sweet', 'dessert', 'pastry', 'cookie', 'biscuit',
    'whiskey', 'whisky', 'bourbon', 'rum', 'wine', 'beer', 'spirit', 'gin', 'vodka',
    'candle', 'wax', 'soap', 'perfume', 'fragrance', 'scent', 'scented',
    'butter', 'cheese', 'sauce', 'honey', 'ice cream', 'milk', 'yogurt',
    'flavor', 'flavour', 'texture', 'crisp', 'creamy', 'soft', 'warmth', 'comfort',
  ];

  // Products whose value is demonstrable by visible transformation or sensory reaction
  const ugcKeywords = [
    'serum', 'cream', 'moisturizer', 'lotion', 'sunscreen', 'spf',
    'perfume', 'fragrance', 'cologne', 'eau de',
    'foundation', 'makeup', 'lipstick', 'mascara', 'eyeshadow', 'blush', 'concealer',
    'hair mask', 'shampoo', 'conditioner', 'hair oil',
    'acne', 'skincare', 'anti-aging', 'wrinkle', 'brightening', 'toner',
    'probiotic', 'vitamin', 'supplement', 'protein powder',
    'teeth whitening', 'whitening',
    'weight loss', 'slimming', 'detox',
  ];

  let craftScore = 0;
  let sensoryScore = 0;
  let ugcScore = 0;
  for (const kw of craftKeywords) { if (haystack.includes(kw)) craftScore++; }
  for (const kw of sensoryKeywords) { if (haystack.includes(kw)) sensoryScore++; }
  for (const kw of ugcKeywords)   { if (haystack.includes(kw)) ugcScore++; }

  if (ugcScore > sensoryScore && ugcScore > craftScore) return 'ugc';
  if (sensoryScore >= craftScore) return 'sensory';

  // Craft wins ties for hard goods — safer than forcing a problem/solution arc
  return 'craft';
}

// ─── Product Image Analysis (GPT-4o Vision) ───────────────────────────────────

export interface ProductImageAnalysis {
  whatItIs: string;          // e.g. "a cylindrical tin of oats"
  productCategory: string;   // e.g. "food & nutrition"
  primaryColor: string;      // dominant color of product/packaging
  keyColors: string[];       // all notable colors
  texture: string;           // e.g. "matte, metallic lid"
  packaging: string;         // e.g. "cylindrical tin with kraft-paper label"
  brandElements: string;     // visible logo, text, markings
  visualDescriptor: string;  // dense single-sentence visual fingerprint for Veo prompt injection
}

/**
 * Uses GPT-4o Vision to analyze the uploaded product image.
 * Returns a structured visual description injected into Veo prompts
 * so the model generates clips featuring the ACTUAL product — correct color, shape, packaging.
 * This does NOT pass the image to Veo directly. It extracts context for text prompts.
 */
export async function analyzeProductImage(imageUrl: string): Promise<ProductImageAnalysis> {
  const fallback: ProductImageAnalysis = {
    whatItIs: 'consumer product',
    productCategory: 'product',
    primaryColor: 'neutral',
    keyColors: ['neutral'],
    texture: 'smooth',
    packaging: 'standard packaging',
    brandElements: 'brand logo',
    visualDescriptor: 'consumer product with standard packaging',
  };

  try {
    const res = await openai.chat.completions.create({
      model: 'gpt-4o',
      max_tokens: 400,
      response_format: { type: 'json_object' },
      messages: [
        {
          role: 'system',
          content: `You are a visual analyst for ad production.
Describe a product image in structured JSON so a video AI model can recreate the product accurately in generated footage.
Be extremely specific about colors, textures, shapes, and distinguishing features.
Return ONLY valid JSON.`,
        },
        {
          role: 'user',
          content: [
            {
              type: 'image_url',
              image_url: { url: imageUrl, detail: 'high' },
            },
            {
              type: 'text',
              text: `Analyze this product image and return JSON with exactly these fields:
{
  "whatItIs": "one-line description of what the product is",
  "productCategory": "category (e.g. food, footwear, skincare, electronics)",
  "primaryColor": "the single most dominant color of the product or packaging",
  "keyColors": ["array", "of", "all", "notable", "colors"],
  "texture": "surface texture description",
  "packaging": "packaging shape and material description",
  "brandElements": "any visible brand name, logo, or text on the product",
  "visualDescriptor": "One dense sentence: exact product appearance for a video AI prompt — color + shape + texture + distinguishing marks. E.g.: 'A cylindrical matte black tin with a gold metallic lid and white kraft-paper label printed with red serif typography.'"
}`,
            },
          ],
        },
      ],
    });

    const raw = res.choices[0]?.message?.content ?? '{}';
    const parsed = JSON.parse(raw);

    return {
      whatItIs: typeof parsed.whatItIs === 'string' ? parsed.whatItIs : fallback.whatItIs,
      productCategory: typeof parsed.productCategory === 'string' ? parsed.productCategory : fallback.productCategory,
      primaryColor: typeof parsed.primaryColor === 'string' ? parsed.primaryColor : fallback.primaryColor,
      keyColors: Array.isArray(parsed.keyColors) ? parsed.keyColors : fallback.keyColors,
      texture: typeof parsed.texture === 'string' ? parsed.texture : fallback.texture,
      packaging: typeof parsed.packaging === 'string' ? parsed.packaging : fallback.packaging,
      brandElements: typeof parsed.brandElements === 'string' ? parsed.brandElements : fallback.brandElements,
      visualDescriptor: typeof parsed.visualDescriptor === 'string' ? parsed.visualDescriptor : fallback.visualDescriptor,
    };
  } catch (err) {
    console.error('[analyzeProductImage] Vision analysis failed, using fallback:', err);
    return fallback;
  }
}

// ─── System Prompt (shared across all generation calls) ───────────────────────

function buildSystemPrompt(category?: string, patterns?: WinningPattern, narrativeStyle: NarrativeStyle = 'ugc'): string {
  const patternBlock = patterns
    ? `\nPROVEN WINNING PATTERNS FOR ${category}:\n${JSON.stringify(patterns, null, 2)}\n`
    : '';

  if (narrativeStyle === 'sensory') {
    return `You are a senior creative director at a top-tier performance marketing agency.
You write director-ready sensory product ads — every shot is a cinematic material or ingredient moment.
${patternBlock}
Rules you NEVER break:
- This is a CATEGORY 2 SENSORY PRODUCT ad.
- Do NOT show humans, hands, faces, or lifestyle context.
- Do NOT show a step-by-step process, tutorial, recipe, assembly, or documentary-style making of.
- Do NOT use before/after, problem/solution, or narrative transformation logic.
- The product world must feel luxurious, tactile, and sensory from the first frame.
- Use only macro, product-only, studio-based visual language.
- Voiceover should be omitted unless the prompt explicitly requires a final title card line.
- No wide shots, no room context, no kitchen/gym/bedroom scenes.
- No generic buzzwords: no "innovative", "seamless", "elevate", "transform", "empower".
- No particle effects, lens flares, glow overlays, smoke, fog, atmospheric haze, mist, or volumetric smoke trails.
- The final frame should be a clean product hero or black end card, not a person or process.
- Every visual choice must be anchored to the product's actual ingredients, materials, texture, or sensory properties.
- Make the viewer feel the product through the screen.`;
  }

  return `You are a senior creative director at a top-tier performance marketing agency.
You write director-ready video ad concepts — every shot described with enough specificity that a video AI can execute without asking a single question.
${patternBlock}
MANDATORY CREATION PROCESS — FOLLOW IN ORDER:
1. ANALYZE: Read the product description, features, and visual identity. Identify the 2-3 most visually demonstrable features or benefits.
2. WRITE ONE STORY: Write a single, continuous 18-second ad story built around those features. Use the DIRECT-RESPONSE marketing framework below.
3. DIVIDE: Split the story into exactly 3 × 6-second scenes that flow naturally from one into the next. Each scene is a chapter, not a standalone ad.
4. DEFINE MASTER STYLE: Write a single masterStyleGuide string (1-2 sentences) that locks the visual identity for all 3 clips.
5. ASSIGN NARRATION: From the overall story, pick short lines only where silence is not enough. Assign null freely — silence is often stronger.

DIRECT-RESPONSE 18-SECOND FRAMEWORK — NON-NEGOTIABLE FOR UGC ARC:
- Scene 1 (0-6s) THE HOOK & PROBLEM: Instantly show the viewer a pain they recognise. No product yet. One sharp question or visual tension.
  Example narration: "Love your morning coffee, but hate the sugar crash?" (7 words)
- Scene 2 (6-12s) THE SOLUTION & EDUCATION: Product is actively solving the problem. Show HOW it works — demonstrate the feature, not just show the box.
  Example narration: "True Sweet. Natural Monk Fruit. Zero calories, zero guilt." (9 words)
- Scene 3 (12-18s) THE HERO & CTA: Product hero shot with natural motion. The emotional payoff. One clean CTA.
  Example narration: "Bake it, stir it, love it. Upgrade today." (8 words)

MASTER STYLE GUIDE — CRITICAL:
- Generate a masterStyleGuide field: one tightly written string (max 3 sentences) that specifies:
  1. Lighting type and quality (e.g. "Bright soft morning light, soft box, warm fill")
  2. Color grade and palette (e.g. "Warm white and natural wood tones, +20% saturation")
  3. Camera style (e.g. "Handheld, slight push-in on subject, 35mm equivalent")
- This EXACT string will be prepended to all 3 Veo generation prompts to prevent lighting and color mismatches between clips.
- Be specific. Vague guides like 'cinematic and warm' are not acceptable.

ONE STORY — NON-NEGOTIABLE:
- ONE character (if human presence needed — specify exact age, look, clothing) or no character for product-only ads. Same character appears in all 3 scenes.
- ONE visual world — same setting family, same lighting mood, same color grade across all 3 scenes. No unmotivated location jumps.
- Scene 2 continues directly from where Scene 1 ended. Scene 3 resolves what Scene 1 set up.
- A viewer watching all 3 clips back-to-back must feel ONE unbroken 18-second ad — not 3 separate shots.
- Visual style (camera, colorGrade, lighting) must be identical across ALL scenes.

NARRATION — STRICT RULES:
- Maximum 20 words per scene narration line. Aim for 12–18 words. Every word must earn its place.
- Plain English only. BANNED WORDS: effortless, transformative, elevate, empower, seamless, journey, experience, innovative, revolutionary, game-changing, discover, embrace, unleash, unlock.
- Mix specific facts/features with emotional pull. Good narration is a fact delivered with feeling.
- GOOD: "Twenty grams of clean protein, zero compromise, ready in thirty seconds." / "Zero sulphates. Twice the volume. Your hair finally gets what it deserves."
- BAD: "Transform your routine effortlessly." / "Experience the difference today."
- null is valid and often stronger. Assign silence where visuals carry the moment alone.
- fullScript = all assigned lines joined in order. Target 40–65 words total — enough for 14–18 seconds of natural speech.

FEATURE DEMONSTRATION — MANDATORY:
- Features must be SHOWN on screen AND NAMED in narration. If "waterproof" — show product in water AND narrate "fully waterproof". If "20g protein" — show a physical/active moment AND narrate "twenty grams of protein".
- Scene 2 narration MUST explicitly name at least ONE feature by its exact wording (the number, the name, the claim). If features list says "20g protein", narration must say "twenty grams of protein" or "20 grams of protein" — not just imply it.
- If features include a number (20g, 48h, 0 calories, SPF50), that exact number MUST appear in the scene 2 narration.
- Build the entire story AROUND the product's features. Every scene must physically demonstrate or set up a feature.
- Never describe a feature without showing it visually.

PRODUCT APPEARANCE — CRITICAL:
- The product shown in every clip must match the actual product — same colors, same packaging, same design. Never substitute a generic product.
- Describe the product in visualPrompt.subject using the exact visual details from the PRODUCT VISUAL IDENTITY block provided.

COLOR GRADE ENFORCEMENT: colorGrade must describe WARM, VIBRANT, RICH tones. BANNED: "desaturated", "muted", "monochrome", "black and white", "bleach bypass", "cold", "washed out", "faded". Replace any banned grade with a vibrant alternative.
ATMOSPHERE BAN: doNotInclude must always contain "smoke effects, fog, atmospheric haze, mist, volumetric smoke trails" for every scene.
PHYSICAL ACTION PRECISION: Any action involving a human sense must be anatomically precise. For smell: "presses wrist to nose, mouth closed, slow nasal inhale". For taste: "sips from cup rim, clean contact, no exaggerated mouth movement". Vague words like "inhales", "savours" are BANNED.
- The CTA appears EXACTLY ONCE — in the final scene only. All other scenes have isCTAScene: false.
- Zero generic CTAs: no "Shop now", "Try it today", "Get yours" — CTA must emotionally close the arc.
- DO NOT MAKE IT GENERIC. Every scene must be specific to THIS product, THIS audience, THIS problem.`;
}

function buildThemeConstraints(theme: string): string {
  const t = theme.toLowerCase()

  if (t.includes('minimalist') || t.includes('studio')) {
    return `THEME RULES:
- Setting: Clean studio, solid backgrounds, or architectural spaces ONLY
- No outdoor locations, no nature, no lifestyle contexts
- Lighting: Controlled studio light — soft boxes, rim lights, hard directional
- Color: Single accent color against neutral — NOT monochrome or desaturated
- Props: The product and one intentional prop maximum
- BANNED: forests, trails, grass, sunlight through trees, puddles, mud, running outdoors`
  }

  if (t.includes('luxury') || t.includes('premium')) {
    return `THEME RULES:
- Settings: Marble, glass, dark interiors, penthouse, gallery spaces
- Lighting: Low-key, moody, practicals (candles, city lights)
- Color: Deep rich tones — black, gold, navy, deep burgundy — still VIBRANT, never washed out
- Pacing: Slow, deliberate, every frame composed
- BANNED: bright colors, crowded spaces, fast cuts, outdoor sports, desaturated grade`
  }

  if (t.includes('energy') || t.includes('sport') || t.includes('performance')) {
    return `THEME RULES:
- Settings: Urban, gym, indoor court, streets at dusk — NOT forests or trails
- Lighting: High contrast, dramatic warm shadows
- Color: Punchy, saturated — electric blues, warm oranges, deep blacks
- Editing: Fast cuts, kinetic energy
- BANNED: peaceful nature, slow pace, soft lighting, desaturated tones`
  }

  // fallback — at minimum inject the theme as an explicit constraint
  return `THEME RULES:
- Every creative decision must visually reinforce: "${theme}"
- If a shot could appear in an ad with a different theme, cut it
- Setting, lighting, and editing rhythm must all be consistent with "${theme}"
- Color grade must be VIBRANT and WARM — never desaturated or muted`
}

function buildSensoryThemeConstraints(theme: string): string {
  return `SENSORY THEME RULES:
- Theme: ${theme}
- Setting: studio-only, no lifestyle context, no natural environment, no kitchen or room storytelling
- Camera: extreme macro, push-ins, high-speed impact, shallow depth of field
- Subject: ingredients, materials, textures, steam, liquid, powder, fabric, or surface detail only
- Human presence: forbidden — no hands, faces, bodies, or usage shots
- Narrative: no process, no walkthrough, no before/after, no emotional arc
- Color grade: rich, cinematic, and product-led — choose warm amber, deep mocha, icy blue, or earthy tones as appropriate
- Atmosphere: clean cinematic air only — no smoke effects, fog, atmospheric haze, mist, or volumetric smoke trails
- Audio: if audio is enabled, prioritize tactile ASMR and impact sounds; otherwise keep the visual sequence self-sufficient`
}

// ─── User Prompt Builder ───────────────────────────────────────────────────────

function buildUserPrompt(
  productName: string,
  theme: string,
  targetAudience: string,
  features?: string,
  imageAnalysis?: ProductImageAnalysis,
  narrativeStyle: NarrativeStyle = 'ugc',
): string {
  const themeConstraints = narrativeStyle === 'sensory'
    ? buildSensoryThemeConstraints(theme)
    : buildThemeConstraints(theme)

  const featuresBlock = features?.trim()
    ? narrativeStyle === 'sensory'
      ? `\nPRODUCT INGREDIENT / MATERIAL CUES (treat these as sensory building blocks, not process steps):\n${features}\nRules:\n- Translate each cue into macro textures, ingredient reveals, surface detail, steam, pour, crumble, sheen, or impact\n- Do NOT turn the features into a recipe, assembly sequence, or step-by-step walkthrough\n- Do NOT mention hands, cooking, preparing, making, or assembling`
      : `\nPRODUCT FEATURES (ground every scene in these — interpret them literally):\n${features}\nExamples of literal interpretation:\n- "Mocha" = coffee flavour — show coffee, espresso, warm brown tones, morning ritual\n- "20g protein" = serious nutrition — show physical effort, recovery, real bodies not models\n- "Overnight" = ease — show the effortless prep, wake up to results\nDo NOT use features as adjectives. Make them VISIBLE on screen.`
    : ''

  const productVisualBlock = imageAnalysis
    ? `\nPRODUCT VISUAL IDENTITY (CRITICAL — every scene featuring the product MUST match these specs exactly):
- What it is: ${imageAnalysis.whatItIs}
- Packaging: ${imageAnalysis.packaging}
- Primary color: ${imageAnalysis.primaryColor}
- All colors: ${imageAnalysis.keyColors.join(', ')}
- Texture: ${imageAnalysis.texture}
- Brand elements: ${imageAnalysis.brandElements}
- Full visual descriptor: "${imageAnalysis.visualDescriptor}"
RULE: Any shot that includes the product must match this visual identity. Wrong colors, wrong shape, or wrong packaging = invalid scene. Describe the product in visualPrompt.subject using the exact details above.`
    : ''

  if (narrativeStyle === 'sensory') {
    const sensorySchema = {
      hook: 'Extreme macro sensory opening: ingredient, material, texture, or surface reveal',
      emotion: 'Sensory anticipation',
      narrativeArc: 'macro reveal -> sensory motion/detail -> pure product payoff in one sentence',
      cta: 'A concise final sensory line or title card, not a generic buy-now line',
      visualStyle: {
        camera: 'Extreme macro, push-in, high-speed studio cinematography',
        colorGrade: 'Rich, cinematic sensory grade — warm amber, deep mocha, icy blue, or earthy tones',
        editingRhythm: 'Slow, hypnotic, tactile, with one or two impact beats',
        doNotInclude: 'Hands, faces, bodies, lifestyle context, tutorials, recipes, assembly steps, smoke effects, fog, atmospheric haze, mist, volumetric smoke trails',
      },
      scenes: [
        {
          sceneNumber: 1,
          durationSeconds: 6,
          description: 'Macro ingredient or material reveal',
          visualPrompt: {
            subject: 'Extreme close-up of the product\'s most tactile ingredient, material, or surface detail',
            action: 'Slow push-in that reveals texture, grain, sheen, or structure without showing a process',
            cameraAngle: 'Macro lens, shallow depth of field, studio framing only',
            lighting: 'Dramatic rim light with a clean dark background and rich contrast',
            colorGrade: 'Warm amber or deep mocha sensory grade with rich highlights',
            doNotInclude: 'Hands, faces, lifestyle context, kitchen or room context, process steps, smoke effects, fog, haze',
          },
          narration: null,
          onScreenText: null,
          isCTAScene: false,
          emotionBeat: 'Immediate tactile curiosity',
        },
        {
          sceneNumber: 2,
          durationSeconds: 6,
          description: 'Sensory motion or impact moment',
          visualPrompt: {
            subject: 'The product materials in motion — pour, crumble, steam, flex, impact, or scatter',
            action: 'Slow-motion sensory event that makes texture and quality feel physical',
            cameraAngle: 'Close, kinetic macro angle with shallow depth of field',
            lighting: 'Single-source studio light with strong highlights and deep shadow shape',
            colorGrade: 'Rich cinematic color with a luxurious product-led palette',
            doNotInclude: 'Hands, faces, lifestyle context, sequence of steps, tutorial behavior, smoke effects, fog, haze',
          },
          narration: null,
          onScreenText: null,
          isCTAScene: false,
          emotionBeat: 'The viewer feels the texture and quality',
        },
        {
          sceneNumber: 3,
          durationSeconds: 6,
          description: 'Pure product hero payoff and end card',
          visualPrompt: {
            subject: 'A clean hero shot of the product or the finished sensory material world',
            action: 'Hold on the most appetizing, tactile, or luxurious frame with no process shown',
            cameraAngle: 'Static hero framing, macro detail still dominant',
            lighting: 'Elegant studio lighting with rich contrast and precise highlights',
            colorGrade: 'Deep, saturated, premium final-frame color grade',
            doNotInclude: 'Hands, faces, lifestyle context, process steps, documentary framing, smoke effects, fog, haze',
          },
          narration: null,
          onScreenText: 'Experience it.',
          isCTAScene: true,
          emotionBeat: 'Clean sensory closure',
        },
      ],
      voiceoverScript: {
        fullScript: '',
        voiceTone: 'No voiceover',
        sceneAssignments: {
          scene_1: null,
          scene_2: null,
          scene_3: null,
        },
      },
      voiceType: { gender: 'female', tone: 'calm', pace: 'medium' },
      musicMood: 'calm',
      tagline: 'Experience it.',
    }

    return `Product: ${productName}
Target Audience: ${targetAudience}
Narrative Style: SENSORY — follow the arc below exactly.
${productVisualBlock}
${featuresBlock}
THEME: ${theme}
THEME IS THE HIGHEST PRIORITY CONSTRAINT. Every scene, lighting choice, camera angle, and setting must serve this theme.
${themeConstraints}

SENSORY MENTAL MODEL:
- Category 2 = sensation, not story
- No human action, no process, no walkthrough, no documentary framing
- Show materials, ingredients, texture, motion, and the sensory payoff only
- Keep the ad visually self-sufficient in 8 seconds of feeling, not explanation

STRUCTURE — NON-NEGOTIABLE:
- Exactly 3 scenes. No more. No fewer.
- Every scene is exactly 6 seconds. durationSeconds must be 6 for all scenes.
- No voiceover unless the final frame is a very short title card line.
- scene_3 is the ONLY CTA scene. scenes 1 and 2 have isCTAScene: false.

Generate a director-ready sensory video ad concept. Return ONLY valid JSON — no markdown, no explanation.

JSON schema (follow exactly):
${JSON.stringify(sensorySchema, null, 2)}`
  }

  // ── ARC-SPECIFIC SCENE TEMPLATES ──────────────────────────────────────────

  const schema = {
    hook: "Exact first 2-second shot: subject + action + camera angle — must be a specific action",
    emotion: "Single core emotion targeted",
    narrativeArc: narrativeStyle === 'ugc'
      ? "problem → product-in-action → emotional-resolution in one sentence"
      : "raw-material-origin → craft-in-action → product-in-the-world in one sentence",
    cta: "Emotionally closes the arc — NOT a generic buy-now line",
    visualStyle: {
      camera: "Consistent camera style for entire ad",
      colorGrade: "WARM and VIBRANT grade consistent for entire ad — no desaturation",
      editingRhythm: narrativeStyle === 'ugc' ? "Pace and cut style" : "Consider fast editorial cuts for making scenes, slow reveal for final product",
      doNotInclude: "smoke effects, fog, atmospheric haze, mist, plus any other visual elements banned from entire ad",
    },
    scenes: narrativeStyle === 'ugc' ? [
      {
        sceneNumber: 1,
        durationSeconds: 6,
        description: "Opening hook — a specific human problem, NOT a product shot",
        visualPrompt: {
          subject: "A real person experiencing the specific problem this product solves",
          action: "A concrete physical action showing the frustration or tension",
          cameraAngle: "Camera angle that serves the scene's emotional intent",
          lighting: "Lighting that matches the visual style — must be WARM and VIBRANT",
          colorGrade: "Warm, vibrant color grade — e.g. 'golden hour warmth, rich midtones, punchy shadows'",
          doNotInclude: "The product itself, any solution — this is the PROBLEM scene. smoke effects, fog, haze",
        },
        narration: null,
        onScreenText: null,
        isCTAScene: false,
        emotionBeat: "Viewer recognizes their own frustration — they lean in",
      },
      "// scene 2 — product actively solving the problem, durationSeconds: 6",
      "// scene 3 — emotional resolution + CTA (human transformation visible), durationSeconds: 6, isCTAScene: true",
    ] : [
      {
        sceneNumber: 1,
        durationSeconds: 6,
        description: "ORIGIN / RAW MATERIAL — where this product begins. No full product reveal yet.",
        visualPrompt: {
          subject: "The raw source material, ingredient, or natural origin of this product — almost abstract, textural",
          action: "Extreme close-up revealing texture and material quality — something the viewer has never seen this closely before",
          cameraAngle: "Macro lens, ultra-close-up — fill the frame with texture, no context yet",
          lighting: "Dramatic directional light that reveals material texture — shadows accentuate grain, fiber, or surface",
          colorGrade: "Rich, deep tones that communicate premium material — warm if natural, cool if technical",
          doNotInclude: "The finished product, any human faces, generic product shot, smoke effects, fog, haze",
        },
        narration: null,
        onScreenText: null,
        isCTAScene: false,
        emotionBeat: "Viewer is intrigued — 'what IS this?' — immediate curiosity hook",
      },
      "// scene 2 — THE CRAFT IN ACTION: hands, tools, process. Fast editorial cuts. Multiple angles. Energy of making. durationSeconds: 6",
      "// scene 3 — FINISHED PRODUCT IN THE WORLD: the product worn/used/consumed in a powerful real-world moment. Human connection. CTA. durationSeconds: 6, isCTAScene: true",
    ],
    voiceoverScript: {
      fullScript: "All narration lines joined in order. Target 40–65 words total. Plain English. No buzzwords. Natural speech pacing — deliverable in 14–18 seconds.",
      voiceTone: narrativeStyle === 'ugc' ? "Calm, direct, human — like a friend stating a fact" : "Measured, precise — like a craftsman who knows their work",
      sceneAssignments: {
        scene_1: narrativeStyle === 'ugc' ? "10–18 WORDS — state the problem or tension with emotional pull, or null for silence" : "MAX 15 WORDS — name the raw material or origin, or null",
        scene_2: "14–20 WORDS — MUST name at least one feature by exact wording (number, name, or claim). State what the product does and why it matters.",
        scene_3: "10–16 WORDS — state the outcome or result. Emotionally closes the arc. Include the CTA.",
      },
    },
    voiceType: { gender: "female", tone: "calm", pace: "medium" },
    musicMood: narrativeStyle === 'ugc' ? "upbeat" : "dramatic",
    tagline: "Memorable closing line — spoken, not generic",
  };

  // Arc-specific structure instructions
  const structureBlock = narrativeStyle === 'ugc'
    ? `NARRATIVE ARC: UGC / DIRECT-RESPONSE
Remember: write the full 18-second story first using the DIRECT-RESPONSE FRAMEWORK, then divide. The arc is the structure of your story.
- Scene 1 (0-6s) THE HOOK & PROBLEM: A specific, relatable pain point the viewer lives. No product yet. End with an implicit question.
  Timing note: Narration should be 10–18 words, deliverable in ~5 seconds, leaving 1 second of visual tension.
- Scene 2 (6-12s) THE SOLUTION: Product IN ACTION — visibly solving the problem. Show HOW it works (demonstrate the feature on screen). This is the education beat.
  Timing note: Narration MUST name at least one feature by exact wording. Target 14–20 words.
- Scene 3 (12-18s) THE HERO & CTA: Emotional payoff. Product hero shot with natural motion (camera pan, ingredient drop). Clean, specific CTA that closes the arc emotionally.
  Timing note: Narration target 10–16 words. CTA is ONE line — not two.`
    : `NARRATIVE ARC: CRAFT / ORIGIN STORY
Remember: write the full 18-second story first, then divide. The arc is the structure of your story.
- Scene 1 (0-6s): RAW MATERIAL or ORIGIN — extreme close-up of source material. Almost abstract, textural. The viewer wonders 'what is this?'
- Scene 2 (6-12s): THE CRAFT IN ACTION — the making. Show skill, precision, tools, process. Fast editorial cuts across multiple angles of the craft.
- Scene 3 (12-18s): PRODUCT IN THE WORLD — the finished product in one powerful real-world moment. Quality made visible.`;

  return `Product: ${productName}
Target Audience: ${targetAudience}
Narrative Style: ${narrativeStyle.toUpperCase()} — follow the arc below exactly.
${productVisualBlock}
${featuresBlock}
THEME: ${theme}
THEME IS THE HIGHEST PRIORITY CONSTRAINT. Every scene, lighting choice, camera angle, and setting must serve this theme.
${themeConstraints}

${structureBlock}

STRUCTURE — NON-NEGOTIABLE:
- Exactly 3 scenes. No more. No fewer.
- Every scene is exactly 6 seconds. durationSeconds must be 6 for all scenes.
- Total ad duration: 18 seconds.
- Voiceover per scene must be writable in under 6 seconds of audio (~12-14 words max per scene).
- scene_3 is the ONLY CTA scene. scenes 1 and 2 have isCTAScene: false.

Generate a director-ready video ad concept. Return ONLY valid JSON — no markdown, no explanation.

JSON schema (follow exactly):
${JSON.stringify({ ...schema, masterStyleGuide: 'Exact lighting type. Exact color grade and palette. Exact camera style. Max 3 sentences total. This string will be prepended verbatim to all 3 Veo video generation prompts.' }, null, 2)}`;
}


function buildFallbackScene(sceneNumber: number, productName: string, narrativeStyle: NarrativeStyle = 'ugc') {
  const isFirst = sceneNumber === 1;
  const isSecond = sceneNumber === 2;

  if (narrativeStyle === 'sensory') {
    return {
      sceneNumber,
      durationSeconds: 6 as const,
      description: isFirst ? 'Macro ingredient or material reveal' : isSecond ? 'Sensory motion moment' : 'Pure product hero payoff',
      visualPrompt: {
        subject: isFirst ? 'Extreme close-up of the product\'s ingredient or material texture' : isSecond ? 'The materials in motion, pour, flex, crumble, or steam' : productName,
        action: isFirst ? 'Slow push-in that reveals texture and detail' : isSecond ? 'A dramatic sensory impact or motion beat' : 'Hold on a clean hero frame with no process shown',
        cameraAngle: 'Macro studio framing',
        lighting: 'Dramatic studio lighting — rich and high contrast',
        colorGrade: 'Rich cinematic sensory color',
        doNotInclude: 'Hands, faces, lifestyle context, process steps, smoke effects, fog, haze',
      },
      narration: null,
      onScreenText: isFirst ? null : (isSecond ? null : 'Experience it.'),
      isCTAScene: false,
      emotionBeat: isFirst ? 'Immediate tactile curiosity' : isSecond ? 'Sensory immersion' : 'Clean sensory closure',
    };
  }

  return {
    sceneNumber,
    durationSeconds: 6 as const, // always 6 seconds (Veo supported)
    description: isFirst ? 'Opening hook — human problem scene' : isSecond ? 'Product in action' : 'Emotional resolution',
    visualPrompt: {
      subject: isFirst ? 'A person experiencing the problem this product solves' : isSecond ? productName : 'A person with visible positive emotion',
      action: isFirst ? 'Concrete physical action showing the frustration' : isSecond ? 'Using the product in a specific, purposeful way' : 'Reacting to the positive outcome',
      cameraAngle: 'Cinematic commercial framing',
      lighting: 'Warm, high-contrast lighting — rich and vibrant',
      colorGrade: 'Warm golden tones, punchy midtones, rich shadows — full color',
      doNotInclude: 'Desaturated tones, black and white, lens flares, floating product renders',
    },
    narration: sceneNumber === 3 ? 'The moment that changes everything.' : null,
    onScreenText: null,
    isCTAScene: false,
    emotionBeat: isFirst ? 'Immediate recognition — the viewer knows this frustration' : isSecond ? 'Rising anticipation' : 'Satisfying relief',
  };
}

function normalizeAdConceptCandidate(parsed: unknown, productName: string, narrativeStyle: NarrativeStyle = 'ugc'): unknown {
  const candidate = typeof parsed === 'object' && parsed !== null ? (parsed as Record<string, unknown>) : {};

  // Always exactly 3 scenes — truncate extras, pad missing with nulls
  const rawScenes = Array.isArray(candidate.scenes) ? [...candidate.scenes].slice(0, 3) : [];
  while (rawScenes.length < 3) {
    rawScenes.push(null);
  }

  const normalizedScenes = rawScenes.map((rawScene, index) => {
    const sceneNumber = index + 1;
    const fallback = buildFallbackScene(sceneNumber, productName, narrativeStyle);
    const scene = typeof rawScene === 'object' && rawScene !== null ? (rawScene as Record<string, unknown>) : {};
    const visual = typeof scene.visualPrompt === 'object' && scene.visualPrompt !== null
      ? (scene.visualPrompt as Record<string, unknown>)
      : {};

    // Sanitize colorGrade — replace banned values with a vibrant alternative
    const BANNED_GRADES = /desaturat|muted|monochrom|black.*white|bleach.bypass|washed.out|faded|cold.grade/i;
    let colorGrade = typeof visual.colorGrade === 'string' ? visual.colorGrade : fallback.visualPrompt.colorGrade;
    if (BANNED_GRADES.test(colorGrade)) {
      colorGrade = 'Warm golden tones, punchy midtones, rich saturated shadows — full vibrant color';
    }

    return {
      sceneNumber,
      durationSeconds: 6 as const, // always locked to 6 — ignore whatever GPT returned
      description: typeof scene.description === 'string' ? scene.description : fallback.description,
      visualPrompt: {
        subject: typeof visual.subject === 'string' ? visual.subject : fallback.visualPrompt.subject,
        action: typeof visual.action === 'string' ? visual.action : fallback.visualPrompt.action,
        cameraAngle: typeof visual.cameraAngle === 'string' ? visual.cameraAngle : fallback.visualPrompt.cameraAngle,
        lighting: typeof visual.lighting === 'string' ? visual.lighting : fallback.visualPrompt.lighting,
        colorGrade,
        doNotInclude: typeof visual.doNotInclude === 'string' ? visual.doNotInclude : fallback.visualPrompt.doNotInclude,
      },
      narration: typeof scene.narration === 'string' || scene.narration === null ? scene.narration : fallback.narration,
      onScreenText: typeof scene.onScreenText === 'string' || scene.onScreenText === null ? scene.onScreenText : (narrativeStyle === 'sensory' && sceneNumber === 3 ? fallback.onScreenText : null),
      isCTAScene: false,
      emotionBeat: typeof scene.emotionBeat === 'string' ? scene.emotionBeat : fallback.emotionBeat,
    };
  });

  normalizedScenes.forEach((scene, index) => {
    scene.isCTAScene = index === normalizedScenes.length - 1;
  });

  const voiceover = typeof candidate.voiceoverScript === 'object' && candidate.voiceoverScript !== null
    ? (candidate.voiceoverScript as Record<string, unknown>)
    : {};
  const voiceAssignments = typeof voiceover.sceneAssignments === 'object' && voiceover.sceneAssignments !== null
    ? (voiceover.sceneAssignments as Record<string, unknown>)
    : {};

  const sceneAssignments = normalizedScenes.reduce<Record<string, string | null>>((acc, scene) => {
    const key = `scene_${scene.sceneNumber}`;
    const assignment = voiceAssignments[key];
    acc[key] = typeof assignment === 'string' ? assignment : null;
    return acc;
  }, {});

  const fallbackCta = typeof candidate.cta === 'string' ? candidate.cta : 'See what happens when you try it.';
  const lastSceneKey = `scene_${normalizedScenes.length}`;
  if (!sceneAssignments[lastSceneKey]) {
    sceneAssignments[lastSceneKey] = narrativeStyle === 'sensory' ? null : fallbackCta;
  }

  const visualStyle = typeof candidate.visualStyle === 'object' && candidate.visualStyle !== null
    ? (candidate.visualStyle as Record<string, unknown>)
    : {};
  const voiceType = typeof candidate.voiceType === 'object' && candidate.voiceType !== null
    ? (candidate.voiceType as Record<string, unknown>)
    : {};

  // Sanitize top-level colorGrade too
  const BANNED_GRADES = /desaturat|muted|monochrom|black.*white|bleach.bypass|washed.out|faded/i;
  let topColorGrade = typeof visualStyle.colorGrade === 'string' ? visualStyle.colorGrade : 'Warm golden tones, punchy midtones, rich color — full saturation';
  if (BANNED_GRADES.test(topColorGrade)) {
    topColorGrade = 'Warm golden tones, punchy midtones, rich color — full saturation';
  }

  return {
    hook: typeof candidate.hook === 'string' ? candidate.hook : `A striking opening moment for ${productName}`,
    emotion: typeof candidate.emotion === 'string' ? candidate.emotion : 'Anticipation',
    narrativeArc: typeof candidate.narrativeArc === 'string' ? candidate.narrativeArc : 'problem -> product-in-action -> emotional-resolution',
    cta: fallbackCta,
    visualStyle: {
      camera: typeof visualStyle.camera === 'string' ? visualStyle.camera : 'Cinematic handheld with intentional closeups',
      colorGrade: topColorGrade,
      editingRhythm: typeof visualStyle.editingRhythm === 'string' ? visualStyle.editingRhythm : 'Fast-open then settle into rhythmic cuts',
      doNotInclude: typeof visualStyle.doNotInclude === 'string' ? visualStyle.doNotInclude : 'Lens flares, floating product renders, generic b-roll, desaturated tones',
    },
    scenes: normalizedScenes,
    voiceoverScript: {
      fullScript: typeof voiceover.fullScript === 'string' ? voiceover.fullScript : (narrativeStyle === 'sensory' ? '' : 'A concise, emotional script that matches each scene.'),
      voiceTone: typeof voiceover.voiceTone === 'string' ? voiceover.voiceTone : (narrativeStyle === 'sensory' ? 'No voiceover' : 'Confident and human'),
      sceneAssignments,
    },
    voiceType: {
      gender: voiceType.gender,
      tone: voiceType.tone,
      pace: voiceType.pace,
    },
    musicMood: candidate.musicMood,
    tagline: typeof candidate.tagline === 'string' ? candidate.tagline : 'The moment it clicks, everything changes.',
    // Preserve masterStyleGuide if GPT returned it (used for visual continuity across Veo prompts)
    ...(typeof candidate.masterStyleGuide === 'string' ? { masterStyleGuide: candidate.masterStyleGuide } : {}),
  };
}

function buildIdeationPrompt(theme: string, productDescription: string): string {
  return `Product: ${productDescription}
Theme/Tone: ${theme}

Generate a sharp, scroll-stopping ad concept summary in one paragraph.
Return ONLY valid JSON with this exact shape:
{
  "idea": "A concise 3-5 sentence idea with a single hook, the core emotion, and the payoff"
}`;
}

// ─── Core Generation (single function, all paths) ─────────────────────────────

async function generateAdConceptRaw(
  productName: string,
  theme: string,
  targetAudience: string,
  category?: string,
  patterns?: WinningPattern,
  features?: string,
  imageAnalysis?: ProductImageAnalysis,
  narrativeStyle?: NarrativeStyle,
): Promise<AdConcept> {
  let lastErr: unknown = null;

  // Auto-detect narrative style if not explicitly provided
  const resolvedStyle: NarrativeStyle = narrativeStyle
    ?? detectNarrativeStyle(productName, features ?? '', imageAnalysis?.productCategory);

  console.log(`[AI] Narrative style: ${resolvedStyle} (product: ${productName})`);

  // Category 2 sensory products use a strict 3-step prompt chain:
  // 1) product analysis -> 2) video brief generation -> 3) quality gate.
  if (resolvedStyle === 'sensory') {
    const productDescription = [
      productName,
      features?.trim() ? `Features: ${features}` : null,
      imageAnalysis?.productCategory ? `Category hint: ${imageAnalysis.productCategory}` : null,
      targetAudience?.trim() ? `Target audience: ${targetAudience}` : null,
      theme?.trim() ? `Theme/Tone: ${theme}` : null,
    ]
      .filter(Boolean)
      .join('. ');

    const chainResult = await runCategory2PromptChain(productDescription);
    return buildCategory2ConceptFromChain(productName, targetAudience, chainResult);
  }

  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await openai.chat.completions.create({
        model: 'gpt-4o',                          // consistent across all paths
        temperature: 1.0,
        max_tokens: 2000,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: buildSystemPrompt(category, patterns, resolvedStyle) },
          { role: 'user', content: buildUserPrompt(productName, theme, targetAudience, features, imageAnalysis, resolvedStyle) },
        ],
      });

      const raw = res.choices[0]?.message?.content ?? '{}';
      const parsed = JSON.parse(raw);
      const normalized = normalizeAdConceptCandidate(parsed, productName, resolvedStyle);
      return AdConceptSchema.parse(normalized);
    } catch (err) {
      lastErr = err;
      console.error(`Ad concept gen failed (attempt ${attempt}/3):`, err);
      await new Promise(r => setTimeout(r, 500 * attempt));
    }
  }

  throw new Error(`Failed to generate ad concept: ${(lastErr as Error)?.message ?? lastErr}`);
}


// ─── Public API ───────────────────────────────────────────────────────────────

/** Basic generation — theme + product only */
export async function generateAdConcept(
  productName: string,
  theme: string,
  targetAudience: string = 'general audience',
  features?: string,
  imageAnalysis?: ProductImageAnalysis,
  narrativeStyle?: NarrativeStyle,
): Promise<AdConcept> {
  return generateAdConceptRaw(productName, theme, targetAudience, undefined, undefined, features, imageAnalysis, narrativeStyle);
}

/** Competitive intelligence generation — uses winning patterns */
export async function generateAdConceptWithPatterns(
  productName: string,
  theme: string,
  category: string,
  targetAudience: string,
  patterns: WinningPattern,
  features?: string,
  imageAnalysis?: ProductImageAnalysis,
  narrativeStyle?: NarrativeStyle,
): Promise<AdConcept> {
  return generateAdConceptRaw(productName, theme, targetAudience, category, patterns, features, imageAnalysis, narrativeStyle);
}

// ─── Pipeline Helper — maps AdConcept scenes to your video gen calls ──────────

export function buildClipJobs(concept: AdConcept) {
  return concept.scenes.map((scene) => ({
    sceneNumber: scene.sceneNumber,
    durationSeconds: scene.durationSeconds,

    // Flat visual prompt string for Kling/Veo — built from structured fields
    videoGenPrompt: [
      scene.visualPrompt.subject,
      scene.visualPrompt.action,
      scene.visualPrompt.cameraAngle,
      scene.visualPrompt.lighting,
      scene.visualPrompt.colorGrade,
      `AVOID: ${scene.visualPrompt.doNotInclude}`,
    ].join('. '),

    // VO line from unified script — never independently generated per clip
    narration: concept.voiceoverScript.sceneAssignments[`scene_${scene.sceneNumber}`] ?? null,
    voiceTone: concept.voiceoverScript.voiceTone,
    voiceType: concept.voiceType,

    // CTA is null for all scenes except the last
    ctaText: scene.isCTAScene ? concept.cta : null,
    onScreenText: scene.onScreenText,

    emotionBeat: scene.emotionBeat,
    musicMood: concept.musicMood,
  }));
}

export async function generateIdeationPrompt(
  theme: string,
  productDescription: string,
): Promise<IdeationPromptResult> {
  const completion = await openai.chat.completions.create({
    model: 'gpt-4o',
    temperature: 0.9,
    max_tokens: 250,
    response_format: { type: 'json_object' },
    messages: [
      {
        role: 'system',
        content: `You are a senior creative director.
Write a single sharp ad concept summary. Keep it specific, visual, and non-generic. Return only JSON.`,
      },
      {
        role: 'user',
        content: buildIdeationPrompt(theme, productDescription),
      },
    ],
  });

  const raw = completion.choices[0]?.message?.content || '{"idea":"A creative ad"}';
  const parsed = JSON.parse(raw);
  return {
    idea: typeof parsed.idea === 'string' ? parsed.idea : 'A creative ad',
  };
}